apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploykf-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: deploykf-app-of-apps
    app.kubernetes.io/part-of: deploykf
spec:
  project: "default"
  source:
    repoURL: "https://github.com/deployKF/deployKF.git"
    targetRevision: "v0.1.5"
    path: "."

    plugin:
      name: "deploykf"
      parameters:
        - name: "source_version"
          string: "0.1.5"

        - name: "values_files"
          array:
            - "./sample-values.yaml"

        - name: "values"
          string: |
            ## --------------------------------------------------------------------------------
            ##                                      argocd
            ## --------------------------------------------------------------------------------
            argocd:
              namespace: argocd
              project: default

            ## --------------------------------------------------------------------------------
            ##                                    kubernetes
            ## --------------------------------------------------------------------------------
            kubernetes:
              {}

            ## --------------------------------------------------------------------------------
            ##                              deploykf-dependencies
            ## --------------------------------------------------------------------------------
            deploykf_dependencies:

              ## --------------------------------------
              ##             cert-manager
              ## --------------------------------------
              cert_manager:
                {}

              ## --------------------------------------
              ##                 istio
              ## --------------------------------------
              istio:
                charts:
                  istioBase:
                    version: 1.18.7
                  istioDaemon:
                    version: 1.18.7

              ## --------------------------------------
              ##                kyverno
              ## --------------------------------------
              kyverno:
                charts:
                  istioGateway:
                    version: 1.18.7

            ## --------------------------------------------------------------------------------
            ##                                  deploykf-core
            ## --------------------------------------------------------------------------------
            deploykf_core:

              ## --------------------------------------
              ##             deploykf-auth
              ## --------------------------------------
              deploykf_auth:
                {}

              ## --------------------------------------
              ##        deploykf-istio-gateway
              ## --------------------------------------
              deploykf_istio_gateway:
                {}

              ## --------------------------------------
              ##      deploykf-profiles-generator
              ## --------------------------------------
              deploykf_profiles_generator:
                {}

            ## --------------------------------------------------------------------------------
            ##                                   deploykf-opt
            ## --------------------------------------------------------------------------------
            deploykf_opt:

              ## --------------------------------------
              ##            deploykf-minio
              ## --------------------------------------
              deploykf_minio:
                enabled: true
                
                minio:
                  persistence:
                    size: "50Gi"
                    storageClass: "local-path"
                  
                  resources:
                    requests:
                      memory: "512Mi"
                      cpu: "250m"
                    limits:
                      memory: "1Gi"
                      cpu: "500m"

                buckets:
                  - name: "ml-artifacts"
                    versioning: true
                  - name: "lora-adapters"
                    versioning: true
                  - name: "models"
                    versioning: true

              ## --------------------------------------
              ##            deploykf-mysql
              ## --------------------------------------
              deploykf_mysql:
                enabled: true
                
                mysql:
                  persistence:
                    size: "20Gi"
                    storageClass: "local-path"
                  
                  resources:
                    requests:
                      memory: "512Mi"
                      cpu: "250m"
                    limits:
                      memory: "1Gi"
                      cpu: "500m"

            ## --------------------------------------------------------------------------------
            ##                                  kubeflow-tools
            ## --------------------------------------------------------------------------------
            kubeflow_tools:

              ## --------------------------------------
              ##                 katib
              ## --------------------------------------
              katib:
                enabled: true
                
                katibController:
                  enabled: true
                
                katibUI:
                  enabled: true
                
                katibDB:
                  enabled: true

              ## --------------------------------------
              ##               notebooks
              ## --------------------------------------
              notebooks:
                enabled: true
                
                notebookController:
                  enabled: true
                
                notebooksWebApp:
                  enabled: true

              ## --------------------------------------
              ##               pipelines
              ## --------------------------------------
              pipelines:
                enabled: true
                
                kfpApiServer:
                  enabled: true
                
                kfpPersistenceAgent:
                  enabled: true
                
                kfpScheduledWorkflow:
                  enabled: true
                
                kfpUi:
                  enabled: true
                
                kfpViewer:
                  enabled: true
                
                objectStore:
                  provider: "minio"
                  minio:
                    host: "deploykf-minio.deploykf-minio.svc.cluster.local"
                    port: 9000
                    useSSL: false
                    bucket: "ml-artifacts"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
