apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploykf-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: deploykf-app-of-apps
    app.kubernetes.io/part-of: deploykf
spec:
  project: "default"
  source:
    ## source git repo configuration
    ##  - we use the 'deploykf/deploykf' repo so we can read its 'sample-values.yaml'
    ##    file, but you may use any repo (even one with no files)
    ##
    repoURL: "https://github.com/deployKF/deployKF.git"
    targetRevision: "v0.1.5"
    path: "."

    ## plugin configuration
    ##
    plugin:
      name: "deploykf"
      parameters:
        ## the deployKF generator version
        ##  - available versions: https://github.com/deployKF/deployKF/releases
        ##
        - name: "source_version"
          string: "0.1.5"

        ## paths to values files within the `repoURL` repository
        ##  - the values in these files are merged, with later files taking precedence
        ##  - we strongly recommend using 'sample-values.yaml' as the base of your values
        ##    so you can easily upgrade to newer versions of deployKF
        ##
        - name: "values_files"
          array:
            - "./sample-values.yaml"

        ## a string containing the contents of a values file
        ##  - this parameter allows defining values without needing to create a file in the repo
        ##  - these values are merged with higher precedence than those defined in `values_files`
        ##
        - name: "values"
          string: |
            ##
            ## Конфигурация для ML платформы с хранилищем артефактов, пайплайнами и метриками
            ##

            ## --------------------------------------------------------------------------------
            ##                                      argocd
            ## --------------------------------------------------------------------------------
            argocd:
              namespace: argocd
              project: default

            ## --------------------------------------------------------------------------------
            ##                                    kubernetes
            ## --------------------------------------------------------------------------------
            kubernetes:
              {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

            ## --------------------------------------------------------------------------------
            ##                              deploykf-dependencies
            ## --------------------------------------------------------------------------------
            deploykf_dependencies:

              ## --------------------------------------
              ##             cert-manager
              ## --------------------------------------
              cert_manager:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##                 istio
              ## --------------------------------------
              istio:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##                kyverno
              ## --------------------------------------
              kyverno:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

            ## --------------------------------------------------------------------------------
            ##                                  deploykf-core
            ## --------------------------------------------------------------------------------
            deploykf_core:

              ## --------------------------------------
              ##             deploykf-auth
              ## --------------------------------------
              deploykf_auth:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##        deploykf-istio-gateway
              ## --------------------------------------
              deploykf_istio_gateway:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##      deploykf-profiles-generator
              ## --------------------------------------
              deploykf_profiles_generator:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

            ## --------------------------------------------------------------------------------
            ##                                   deploykf-opt
            ## --------------------------------------------------------------------------------
            deploykf_opt:

              ## --------------------------------------
              ##            deploykf-minio (S3-совместимое хранилище для артефактов)
              ## --------------------------------------
              deploykf_minio:
                enabled: true
                
                ## настройки MinIO для хранения LoRA адаптеров и других артефактов
                minio:
                  ## размер хранилища
                  persistence:
                    size: "50Gi"
                    storageClass: "local-path"  # для k3s
                  
                  ## ресурсы для MinIO
                  resources:
                    requests:
                      memory: "512Mi"
                      cpu: "250m"
                    limits:
                      memory: "1Gi"
                      cpu: "500m"

                ## создаем bucket для артефактов ML
                buckets:
                  - name: "ml-artifacts"
                    versioning: true
                  - name: "lora-adapters"
                    versioning: true
                  - name: "models"
                    versioning: true

              ## --------------------------------------
              ##            deploykf-mysql
              ## --------------------------------------
              deploykf_mysql:
                enabled: false  # отключаем MySQL

              ## --------------------------------------
              ##         deploykf-postgresql
              ## --------------------------------------
              deploykf_postgresql:
                enabled: true
                
                postgresql:
                  persistence:
                    size: "15Gi"  # чуть больше для PostgreSQL
                    storageClass: "local-path"  # для k3s
                  
                  ## ресурсы для PostgreSQL
                  resources:
                    requests:
                      memory: "512Mi"
                      cpu: "250m"
                    limits:
                      memory: "1Gi" 
                      cpu: "500m"
                  
                  ## настройки PostgreSQL для ML workloads
                  postgresqlConfiguration:
                    shared_preload_libraries: "pg_stat_statements"
                    max_connections: "200"
                    work_mem: "4MB"
                    maintenance_work_mem: "64MB"

            ## --------------------------------------------------------------------------------
            ##                                  kubeflow-tools
            ## --------------------------------------------------------------------------------
            kubeflow_tools:

              ## --------------------------------------
              ##                 katib (для экспериментов и метрик)
              ## --------------------------------------
              katib:
                enabled: true
                
                ## включаем все компоненты Katib
                katibController:
                  enabled: true
                
                katibUI:
                  enabled: true
                
                katibDB:
                  enabled: true
                
                ## настройка внешней базы данных (PostgreSQL)
                mysql:
                  useExternal: true
                  external:
                    host: "deploykf-postgresql.deploykf-opt.svc.cluster.local"
                    port: 5432
                    database: "katib"
                    driverName: "postgres"

              ## --------------------------------------
              ##               notebooks (Jupyter для разработки)
              ## --------------------------------------
              notebooks:
                enabled: true
                
                ## настройки для notebook серверов
                notebookController:
                  enabled: true
                
                ## веб-интерфейс для управления notebook'ами
                notebooksWebApp:
                  enabled: true

              ## --------------------------------------
              ##               pipelines (для пайплайнов дообучения)
              ## --------------------------------------
              pipelines:
                enabled: true
                
                ## все компоненты пайплайнов
                kfpApiServer:
                  enabled: true
                
                kfpPersistenceAgent:
                  enabled: true
                
                kfpScheduledWorkflow:
                  enabled: true
                
                kfpUi:
                  enabled: true
                
                kfpViewer:
                  enabled: true
                
                ## настройки базы данных для пайплайнов
                kfpDatabase:
                  ## используем внешний PostgreSQL (deploykf_postgresql)
                  external:
                    host: "deploykf-postgresql.deploykf-opt.svc.cluster.local"
                    port: 5432
                    database: "kfp"
                    driverName: "postgres"
                
                ## настройки объектного хранилища
                objectStore:
                  ## используем MinIO
                  provider: "minio"
                  minio:
                    host: "deploykf-minio.deploykf-opt.svc.cluster.local"
                    port: 9000
                    useSSL: false
                    bucket: "ml-artifacts"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
